<?php
/**
 * Title: Ugolini catalogue call to action
 * Slug: ugolini-group/catalogue-cta
 * Categories: ugolini-sections
 * Keywords: catalogue, wholesale
 */
?>
<!-- wp:cover {"url":"https://ugolinigroup.com/wp-content/uploads/2026/08/8800-pesto-alla-genovese-ugolini-gourmet-10.jpg","alt":"Pesto alla genovese Ugolini Gourmet con basilico","dimRatio":62,"overlayColor":"dark-section","isUserOverlayColor":true,"align":"wide","className":"ugolini-catalogue-panel"} --><div class="wp-block-cover alignwide ugolini-catalogue-panel"><span aria-hidden="true" class="wp-block-cover__background has-dark-section-background-color has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Pesto alla genovese Ugolini Gourmet con basilico" src="https://ugolinigroup.com/wp-content/uploads/2026/08/8800-pesto-alla-genovese-ugolini-gourmet-10.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"ugolini-catalogue-panel__copy","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-catalogue-panel__copy"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Catalogo Ugolini Gourmet</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Consulta la gamma dedicata al gusto italiano</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Il catalogo professionale raccoglie la gamma Ugolini Gourmet e i materiali dedicati al consumo e all’ingrosso.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"white","textColor":"text"} --><div class="wp-block-button"><a class="wp-block-button__link has-text-color has-white-background-color has-text-color has-background wp-element-button" href="/contatti/">Richiedi il catalogo</a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline-light"} --><div class="wp-block-button is-style-outline-light"><a class="wp-block-button__link wp-element-button" href="/shop/">Esplora lo shop</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div></div><!-- /wp:cover -->
