<?php
/**
 * Title: La storia Ugolini
 * Slug: ugolini-group/home-story
 * Categories: ugolini-sections
 * Keywords: storia, chi siamo, heritage
 */
?>
<!-- wp:group {"align":"full","className":"ugolini-home-story","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-home-story">
<!-- wp:group {"align":"wide","className":"ugolini-home-story__row","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-home-story__row"><!-- wp:group {"className":"ugolini-home-story__copy","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-home-story__copy"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Una storia di famiglia</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Le radici di una passione italiana</h2><!-- /wp:heading --><!-- wp:paragraph --><p>La storia di Ugolini nasce nei primi anni del Novecento dalla passione di nonno Renato per la terra. Sua figlia Renata portava al mercato prodotti freschi e naturali, preparati senza conservanti: un sapere familiare che ha attraversato le generazioni.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Dopo un secolo di esperienza prende forma Ugolini Gourmet, dove memoria gastronomica e ricerca contemporanea si incontrano.</p><!-- /wp:paragraph --><p class="ugolini-editorial-link"><a href="/shop/">Esplora i prodotti</a></p></div><!-- /wp:group --><!-- wp:group {"className":"ugolini-home-story__gallery","layout":{"type":"default"}} --><div class="wp-block-group ugolini-home-story__gallery"><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigourmet.it/wp-content/uploads/2026/01/fiera-urbani-tartufi-1024x768.jpeg" alt="Roberto Ugolini durante una fiera dedicata al tartufo"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigourmet.it/wp-content/uploads/2023/01/8817-pesto-rosso-ugolini-gourmet-4-683x1024.jpg" alt="Pesto rosso Ugolini Gourmet"/></figure><!-- /wp:image --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"ugolini-home-story__row ugolini-home-story__row--reverse","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-home-story__row ugolini-home-story__row--reverse"><!-- wp:group {"className":"ugolini-home-story__gallery","layout":{"type":"default"}} --><div class="wp-block-group ugolini-home-story__gallery"><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigourmet.it/wp-content/uploads/2023/01/8848-sugo-allarrabbiata-ugolini-gourmet-5.jpg" alt="Sugo all’arrabbiata Ugolini Gourmet"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigourmet.it/wp-content/uploads/2023/01/8831-sugo-tartufo-nero-ugolini-gourmet-4.jpg" alt="Sugo al tartufo nero Ugolini Gourmet"/></figure><!-- /wp:image --></div><!-- /wp:group --><!-- wp:group {"className":"ugolini-home-story__copy","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-home-story__copy"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Esperienza e innovazione</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Dalla ristorazione a una linea gourmet</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Con oltre vent’anni di esperienza nella ristorazione e il confronto con chef stellati, Roberto Ugolini ha trasformato esigenze reali di cucina in prodotti affidabili, funzionali e riconoscibili.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Dalla collaborazione con lo chef Nino Cannavale nascono le prime salse gourmet: specialità al tartufo, proposte vegane e biologiche, referenze Halal e Kosher, tutte accomunate dalla cura per ingredienti e ricette.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"ugolini-home-story__manifesto","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-home-story__manifesto"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Ugolini Gourmet</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Tradizione, esperienza e innovazione per portare in tavola un gusto autentico.</h2><!-- /wp:heading --></div><!-- /wp:group -->
</div><!-- /wp:group -->
