<?php
/**
 * Title: Page — B2B / Wholesale
 * Slug: ugolini-group/page-b2b
 * Categories: ugolini-pages
 * Keywords: b2b, wholesale, restaurant, retail
 * Block Types: core/post-content
 */
?>
<!-- wp:cover {"url":"https://ugolinigroup.com/wp-content/uploads/2026/08/9371-olio-extra-vergine-di-oliva-al-tartufo-bianco-ugolini-gourmet-7-scaled-1.jpg","alt":"Olio extra vergine di oliva al tartufo bianco Ugolini Gourmet","dimRatio":66,"overlayColor":"dark-section","isUserOverlayColor":true,"align":"full","className":"ugolini-page-hero ugolini-page-hero--image ugolini-b2b-hero"} --><div class="wp-block-cover alignfull ugolini-page-hero ugolini-page-hero--image ugolini-b2b-hero"><span aria-hidden="true" class="wp-block-cover__background has-dark-section-background-color has-background-dim-70 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Olio extra vergine di oliva al tartufo bianco Ugolini Gourmet" src="https://ugolinigroup.com/wp-content/uploads/2026/08/9371-olio-extra-vergine-di-oliva-al-tartufo-bianco-ugolini-gourmet-7-scaled-1.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"align":"wide","className":"ugolini-page-hero-content","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-page-hero-content"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Ugolini per i professionisti</p><!-- /wp:paragraph --><!-- wp:post-title {"level":1} /--><!-- wp:paragraph --><p>Condimenti pronti all’uso nati da esperienza nella ristorazione, cultura gastronomica e ricerca della continuità qualitativa.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"white","textColor":"text"} --><div class="wp-block-button"><a class="wp-block-button__link has-text-color has-white-background-color has-text-color has-background wp-element-button" href="/contatti/">Diventa partner</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div></div><!-- /wp:cover -->

<!-- wp:group {"align":"full","className":"ugolini-section ugolini-wholesale-intro","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-wholesale-intro"><!-- wp:group {"align":"wide","className":"ugolini-wholesale-intro__grid","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-wholesale-intro__grid"><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Partnership professionali</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Sei uno chef, ristoratore o distributore?</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Roberto Ugolini ha trasformato oltre vent’anni di esperienza nella ristorazione in una gamma pensata per le esigenze concrete della cucina professionale e della grande distribuzione.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="/contatti/">Parliamo del tuo progetto</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --><!-- wp:list {"className":"ugolini-wholesale-benefits"} --><ul class="wp-block-list ugolini-wholesale-benefits"><li><strong>Standard qualitativo costante</strong><span>Ricette affidabili anche quando cambia la brigata di cucina.</span></li><li><strong>Condimenti pronti all’uso</strong><span>Funzionalità e continuità per il servizio quotidiano.</span></li><li><strong>Ristorazione e distribuzione</strong><span>Una gamma pensata per professionisti, retail e famiglie.</span></li><li><strong>Mercati internazionali</strong><span>Prodotti Made in Italy spediti nel mondo con DHL Express.</span></li></ul><!-- /wp:list --></div><!-- /wp:group --></div><!-- /wp:group -->

<!-- wp:group {"align":"full","className":"ugolini-wholesale-services","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-wholesale-services"><!-- wp:group {"align":"wide","className":"ugolini-wholesale-services__heading","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-wholesale-services__heading"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Un servizio costruito per il tuo lavoro</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Dalla selezione al riordino</h2><!-- /wp:heading --></div><!-- /wp:group --><!-- wp:html -->
<div class="alignwide ugolini-wholesale-services__list">
	<details><summary><span>01</span>Condizioni dedicate</summary><p>Richiedi una proposta costruita sulle esigenze della tua attività.</p></details>
	<details><summary><span>02</span>Ordini online</summary><p>Consulta prodotti e collezioni disponibili direttamente nello shop.</p></details>
	<details><summary><span>03</span>Assistenza commerciale</summary><p>Un contatto dedicato per informazioni e richieste professionali.</p></details>
	<details><summary><span>04</span>Catalogo aggiornato</summary><p>Formati, ingredienti e certificazioni raccolti in modo chiaro.</p></details>
	<details><summary><span>05</span>Spedizioni internazionali</summary><p>Consegne gestite tramite DHL Express nei mercati serviti.</p></details>
	<details><summary><span>06</span>Gamma professionale</summary><p>Referenze per chef, ristorazione, retail e distribuzione.</p></details>
	<details><summary><span>07</span>Riordino semplice</summary><p>Ritrova rapidamente la gamma Ugolini già scelta.</p></details>
</div>
<!-- /wp:html --></div><!-- /wp:group -->

<!-- wp:group {"align":"full","className":"ugolini-b2b-catalogue","layout":{"type":"default"}} --><div class="wp-block-group alignfull ugolini-b2b-catalogue"><!-- wp:pattern {"slug":"ugolini-group/catalogue-cta"} /--></div><!-- /wp:group -->

<!-- wp:group {"align":"full","className":"ugolini-section ugolini-b2b-values","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-b2b-values"><!-- wp:group {"align":"wide","className":"ugolini-value-grid ugolini-value-grid--icons","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-value-grid ugolini-value-grid--icons"><!-- wp:group {"className":"ugolini-value-item","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-value-item"><!-- wp:html --><svg class="ugolini-value-icon" aria-hidden="true" viewBox="0 0 24 24"><path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.78 4.78 4 4 0 0 1-6.74 0 4 4 0 0 1-4.78-4.78 4 4 0 0 1 0-6.75Z"/><path d="m9 12 2 2 4-4"/></svg><!-- /wp:html --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Qualità</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Materie prime selezionate, ricette autentiche e standard elevati e costanti.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"ugolini-value-item","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-value-item"><!-- wp:html --><svg class="ugolini-value-icon" aria-hidden="true" viewBox="0 0 24 24"><path d="m16 16 2 2 4-4"/><path d="M21 10.5V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l2-1.14"/><path d="m7.5 4.27 9 5.15"/><polyline points="3.29 7 12 12 20.71 7"/><line x1="12" x2="12" y1="22" y2="12"/></svg><!-- /wp:html --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Funzionalità</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Condimenti pronti all’uso pensati per mantenere coerenza e continuità in cucina.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"ugolini-value-item","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-value-item"><!-- wp:html --><svg class="ugolini-value-icon" aria-hidden="true" viewBox="0 0 24 24"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="m9 12 2 2 4-4"/></svg><!-- /wp:html --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Made in Italy</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Ricette italiane che incontrano l’innovazione per un gusto riconoscibile e affidabile.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group -->

<!-- wp:group {"align":"full","className":"ugolini-section ugolini-wholesale-audiences","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-wholesale-audiences"><!-- wp:group {"align":"wide","className":"ugolini-section-heading","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-section-heading"><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Con chi lavoriamo</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Una gamma per ogni servizio</h2><!-- /wp:heading --></div><!-- /wp:group --></div><!-- /wp:group --><!-- wp:group {"align":"wide","className":"ugolini-audience-grid","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-audience-grid"><article><span>01</span><h3>Chef professionisti</h3><p>Prodotti affidabili nati dal confronto con le esigenze dell’alta cucina.</p></article><article><span>02</span><h3>Ristorazione</h3><p>Continuità di gusto e rapidità d’uso durante ogni servizio.</p></article><article><span>03</span><h3>Retail e distribuzione</h3><p>Referenze accessibili alle famiglie, con confezioni curate e funzionali.</p></article><article><span>04</span><h3>Mercati internazionali</h3><p>Tradizione italiana, innovazione e spedizioni internazionali.</p></article></div><!-- /wp:group --></div><!-- /wp:group -->

<!-- wp:group {"align":"full","className":"ugolini-wholesale-gallery","layout":{"type":"default"}} --><div class="wp-block-group alignfull ugolini-wholesale-gallery"><!-- wp:group {"className":"ugolini-wholesale-gallery__copy","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-wholesale-gallery__copy"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Un partner per la cucina professionale</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Dalla ricerca alla tavola</h2><!-- /wp:heading --></div><!-- /wp:group --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigourmet.it/wp-content/uploads/2023/01/8848-sugo-allarrabbiata-ugolini-gourmet-5.jpg" alt="Sugo all’arrabbiata Ugolini Gourmet"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigourmet.it/wp-content/uploads/2023/01/8855-pesto-vegano-ugolini-gourmet-8-scaled.jpg" alt="Pesto vegano Ugolini Gourmet"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigourmet.it/wp-content/uploads/2023/01/8831-sugo-tartufo-nero-ugolini-gourmet-4.jpg" alt="Sugo al tartufo nero Ugolini Gourmet"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigourmet.it/wp-content/uploads/2023/01/8824-ragu-alla-bolognese-ugolini-gourmet-10.jpg" alt="Ragù alla bolognese Ugolini Gourmet"/></figure><!-- /wp:image --></div><!-- /wp:group -->

<!-- wp:group {"align":"full","className":"ugolini-section ugolini-wholesale-more","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-wholesale-more"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Più di un fornitore</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Metodo, continuità e ascolto</h2><!-- /wp:heading --></div><!-- /wp:group --><!-- wp:group {"align":"wide","className":"ugolini-wholesale-more__grid","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-wholesale-more__grid"><article><h3>Esperienza gastronomica</h3><p>Oltre vent’anni nella ristorazione trasformati in soluzioni concrete.</p></article><article><h3>Ricerca continua</h3><p>Ricette sviluppate con attenzione a ingredienti, equilibrio e affidabilità.</p></article><article><h3>Una gamma inclusiva</h3><p>Proposte vegane, biologiche e referenze certificate Halal e Kosher.</p></article></div><!-- /wp:group --></div><!-- /wp:group -->

<!-- wp:html -->
<section class="ugolini-b2b-partner" aria-labelledby="ugolini-b2b-partner-title">
	<div class="ugolini-b2b-partner__benefits">
		<p class="ugolini-eyebrow">Vantaggi professionali</p>
		<h2 id="ugolini-b2b-partner-title">Un rapporto costruito sulla tua attività</h2>
		<ul>
			<li>Proposte e condizioni dedicate</li>
			<li>Ordini online dalla gamma disponibile</li>
			<li>Assistenza commerciale diretta</li>
			<li>Formati, ingredienti e certificazioni consultabili</li>
			<li>Spedizioni internazionali con DHL Express</li>
			<li>Referenze per ristorazione, retail e distribuzione</li>
			<li>Riordino semplice dei prodotti già scelti</li>
		</ul>
	</div>
	<form class="ugolini-b2b-form" action="mailto:info@ugolinigroup.com" method="post" enctype="text/plain">
		<header><p class="ugolini-eyebrow">Richieste B2B</p><h2>Sei uno chef, ristoratore o distributore?</h2><p>Raccontaci la tua attività: il team Ugolini ti ricontatterà per approfondire esigenze, gamma e condizioni.</p></header>
		<div class="ugolini-b2b-form__row"><label><span>Nome</span><input type="text" name="Nome" autocomplete="given-name" required></label><label><span>Cognome</span><input type="text" name="Cognome" autocomplete="family-name" required></label></div>
		<label><span>Email</span><input type="email" name="Email" autocomplete="email" required></label>
		<fieldset><legend>Tipologia di attività</legend><label><input type="radio" name="Attività" value="Chef o ristorante" required> Chef / ristorante</label><label><input type="radio" name="Attività" value="Negozio retail"> Negozio retail</label><label><input type="radio" name="Attività" value="Rivenditore online"> Rivenditore online</label><label><input type="radio" name="Attività" value="Grossista o distributore"> Grossista / distributore</label><label><input type="radio" name="Attività" value="Produttore alimentare"> Produttore alimentare</label></fieldset>
		<label><span>Paese</span><input type="text" name="Paese" autocomplete="country-name" required></label>
		<label><span>Telefono</span><input type="tel" name="Telefono" autocomplete="tel"></label>
		<label><span>Descrivi la tua richiesta</span><textarea name="Richiesta" rows="5" required></textarea></label>
		<button type="submit">Invia la richiesta</button>
		<small>L’invio apre il tuo programma di posta: il sito non conserva i dati inseriti.</small>
	</form>
</section>
<!-- /wp:html -->

<!-- wp:pattern {"slug":"ugolini-group/b2b-cta"} /-->
