<?php
/**
 * Title: Page — Blog / Ricette
 * Slug: ugolini-group/page-blog
 * Categories: ugolini-pages
 * Keywords: blog, recipes, archive
 * Block Types: core/post-content
 */
?>
<!-- wp:cover {"url":"https://ugolinigroup.com/wp-content/uploads/2026/08/8886-pesto-rosso-bio-ugolini-gourmet-9-scaled-1.jpg","alt":"Pesto rosso biologico Ugolini Gourmet","dimRatio":70,"overlayColor":"dark-section","isUserOverlayColor":true,"align":"full","className":"ugolini-page-hero ugolini-page-hero--image"} --><div class="wp-block-cover alignfull ugolini-page-hero ugolini-page-hero--image"><span aria-hidden="true" class="wp-block-cover__background has-dark-section-background-color has-background-dim-70 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Pesto rosso biologico Ugolini Gourmet" src="https://ugolinigroup.com/wp-content/uploads/2026/08/8886-pesto-rosso-bio-ugolini-gourmet-9-scaled-1.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"align":"wide","className":"ugolini-page-hero-content","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-page-hero-content"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Journal Ugolini</p><!-- /wp:paragraph --><!-- wp:post-title {"level":1} /--><!-- wp:paragraph --><p>Alimentazione sana, cucina gourmet, ingredienti e tecniche: contenuti originali Ugolini dedicati al gusto e alla cultura della tavola.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div><!-- /wp:cover -->
<!-- wp:group {"align":"full","className":"ugolini-section","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section"><!-- wp:query {"queryId":21,"query":{"perPage":9,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"exclude","inherit":false},"align":"wide"} --><div class="wp-block-query alignwide"><!-- wp:post-template {"className":"ugolini-journal-grid"} --><!-- wp:post-featured-image {"isLink":true} /--><!-- wp:post-terms {"term":"category"} /--><!-- wp:post-title {"isLink":true,"level":3} /--><!-- wp:group {"className":"ugolini-journal-byline","layout":{"type":"flex","flexWrap":"wrap"}} --><div class="wp-block-group ugolini-journal-byline"><!-- wp:post-author-name /--><!-- wp:post-date /--></div><!-- /wp:group --><!-- wp:post-excerpt {"moreText":"Leggi di più →"} /--><!-- /wp:post-template --><!-- wp:query-pagination {"layout":{"type":"flex","justifyContent":"center"}} --><!-- wp:query-pagination-previous {"label":"Precedenti"} /--><!-- wp:query-pagination-numbers /--><!-- wp:query-pagination-next {"label":"Successivi"} /--><!-- /wp:query-pagination --></div><!-- /wp:query --></div><!-- /wp:group -->
