<?php
/**
 * Title: Page — Shop
 * Slug: ugolini-group/page-shop
 * Categories: ugolini-pages
 * Keywords: shop, products, surecart
 * Block Types: core/post-content
 */
?>
<!-- wp:cover {"url":"https://ugolinigroup.com/wp-content/uploads/2026/08/9302-tartufo-estivo-intero-ugolini-gourmet-2-scaled-1.jpg","alt":"Specialità Ugolini Gourmet al tartufo","dimRatio":60,"overlayColor":"dark-section","isUserOverlayColor":true,"align":"full","className":"ugolini-page-hero ugolini-page-hero--image"} --><div class="wp-block-cover alignfull ugolini-page-hero ugolini-page-hero--image"><span aria-hidden="true" class="wp-block-cover__background has-dark-section-background-color has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Specialità Ugolini Gourmet al tartufo" src="https://ugolinigroup.com/wp-content/uploads/2026/08/9302-tartufo-estivo-intero-ugolini-gourmet-2-scaled-1.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"align":"wide","className":"ugolini-page-hero-content","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-page-hero-content"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Ugolini Gourmet</p><!-- /wp:paragraph --><!-- wp:post-title {"level":1} /--><!-- wp:paragraph --><p>Una selezione di salse gourmet, specialità al tartufo e prodotti vegani e biologici, nata dalla passione per la qualità e dalla cura per ogni ingrediente.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div><!-- /wp:cover -->
<!-- wp:pattern {"slug":"ugolini-group/collection-grid"} /-->
<!-- wp:group {"align":"full","className":"ugolini-section ugolini-products-section","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-products-section"><!-- wp:group {"align":"wide","className":"ugolini-section-heading","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-section-heading"><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Catalogo prodotti</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Tutta la gamma Ugolini Gourmet</h2><!-- /wp:heading --></div><!-- /wp:group --></div><!-- /wp:group --><!-- wp:pattern {"slug":"ugolini-group/shop-product-grid"} /--></div><!-- /wp:group -->
<!-- wp:group {"align":"full","className":"ugolini-section ugolini-collection-editorial-section","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-collection-editorial-section"><!-- wp:shortcode -->[ugolini_collection_editorial]<!-- /wp:shortcode --></div><!-- /wp:group -->
<!-- wp:pattern {"slug":"ugolini-group/newsletter"} /-->
