<?php
/**
 * Title: Page — Supporto e informazioni legali
 * Slug: ugolini-group/page-legal
 * Categories: ugolini-pages
 * Keywords: legal, privacy, support
 * Block Types: core/post-content
 */
?>
<!-- wp:cover {"url":"https://ugolinigroup.com/wp-content/uploads/2026/08/8831-sugo-tartufo-nero-ugolini-gourmet-7.jpg","alt":"Sugo al tartufo Ugolini Gourmet con ingredienti italiani","dimRatio":66,"overlayColor":"dark-section","isUserOverlayColor":true,"align":"full","className":"ugolini-page-hero ugolini-page-hero--image"} --><div class="wp-block-cover alignfull ugolini-page-hero ugolini-page-hero--image"><span aria-hidden="true" class="wp-block-cover__background has-dark-section-background-color has-background-dim-70 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Sugo al tartufo Ugolini Gourmet con ingredienti italiani" src="https://ugolinigroup.com/wp-content/uploads/2026/08/8831-sugo-tartufo-nero-ugolini-gourmet-7.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"align":"wide","className":"ugolini-page-hero-content","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-page-hero-content"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Supporto</p><!-- /wp:paragraph --><!-- wp:post-title {"level":1} /--><!-- wp:paragraph --><p>Informazioni per consultare le condizioni del servizio e contattare Ugolini Gourmet.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div><!-- /wp:cover -->
<!-- wp:group {"align":"full","className":"ugolini-section","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section"><!-- wp:group {"align":"wide","className":"ugolini-value-grid","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-value-grid"><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><a href="/privacy-policy/">Privacy policy</a></h3><!-- /wp:heading --><!-- wp:paragraph --><p>Informazioni sul trattamento dei dati personali.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><a href="/cookie-policy/">Cookie policy</a></h3><!-- /wp:heading --><!-- wp:paragraph --><p>Preferenze, servizi e gestione del consenso.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><a href="/termini-e-condizioni/">Termini e condizioni</a></h3><!-- /wp:heading --><!-- wp:paragraph --><p>Condizioni applicabili al sito e agli acquisti.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:pattern {"slug":"ugolini-group/b2b-cta"} /-->
