<?php
/**
 * Title: FAQ page
 * Slug: ugolini-group/page-faq
 * Categories: ugolini-pages
 * Keywords: faq, support
 * Inserter: no
 */
?>
<!-- wp:cover {"url":"https://ugolinigroup.com/wp-content/uploads/2026/08/8831-sugo-tartufo-nero-ugolini-gourmet-7.jpg","alt":"Sugo al tartufo Ugolini Gourmet con ingredienti italiani","dimRatio":68,"overlayColor":"dark-section","isUserOverlayColor":true,"align":"full","className":"ugolini-page-hero ugolini-page-hero--image"} --><div class="wp-block-cover alignfull ugolini-page-hero ugolini-page-hero--image"><span aria-hidden="true" class="wp-block-cover__background has-dark-section-background-color has-background-dim-70 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Sugo al tartufo Ugolini Gourmet con ingredienti italiani" src="https://ugolinigroup.com/wp-content/uploads/2026/08/8831-sugo-tartufo-nero-ugolini-gourmet-7.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"align":"wide","className":"ugolini-page-hero-content","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-page-hero-content"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Supporto</p><!-- /wp:paragraph --><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Domande frequenti</h1><!-- /wp:heading --><!-- wp:paragraph --><p>Prodotti, ordini, account e richieste professionali: le informazioni essenziali per scegliere Ugolini Gourmet.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div><!-- /wp:cover -->

<!-- wp:group {"align":"full","className":"ugolini-section ugolini-faq-page","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-faq-page"><!-- wp:group {"align":"wide","className":"ugolini-faq-sections","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-faq-sections">

<!-- wp:group {"className":"ugolini-faq-section","layout":{"type":"default"}} --><div class="wp-block-group ugolini-faq-section"><div><p class="ugolini-eyebrow">Generale</p><h2 class="wp-block-heading">Ugolini Gourmet</h2></div><div class="wp-block-group ugolini-faq-list">
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Chi è Ugolini Gourmet?</summary><p>Ugolini Gourmet nasce da oltre un secolo di esperienza familiare e dall’incontro tra Roberto Ugolini e lo chef Nino Cannavale. La gamma raccoglie specialità gastronomiche italiane pensate per la tavola e per i professionisti.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Come posso contattare il servizio clienti?</summary><p>Puoi scrivere a <a href="mailto:info@ugolinigroup.com">info@ugolinigroup.com</a>, chiamare il <a href="tel:+393515111273">+39 351 511 1273</a> oppure usare i collegamenti presenti nella pagina Contatti.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Dove si trova Ugolini Gourmet?</summary><p>La sede legale è in Via Tiberina km 9.2, 00060 Riano (RM), Italia. Lo stabilimento principale è in Via Tuscania 9, 01028 Orte (VT).</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>È disponibile una proposta per professionisti e distributori?</summary><p>Sì. Ristorazione, retail e distribuzione possono inviare una richiesta dalla pagina B2B indicando azienda, mercato e tipologia di interesse.</p></details><!-- /wp:details -->
</div></div><!-- /wp:group -->

<!-- wp:group {"className":"ugolini-faq-section","layout":{"type":"default"}} --><div class="wp-block-group ugolini-faq-section"><div><p class="ugolini-eyebrow">Prodotti</p><h2 class="wp-block-heading">Scelta e utilizzo</h2></div><div class="wp-block-group ugolini-faq-list">
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Quali specialità propone Ugolini Gourmet?</summary><p>Lo shop raccoglie sughi, pesti, salse ai funghi e al tartufo, oli al tartufo, conserve e altre specialità della tradizione italiana. Disponibilità e collezioni vengono mostrate nel catalogo prodotti.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Dove trovo ingredienti, allergeni e valori nutrizionali?</summary><p>Le informazioni verificate sono riportate nella scheda del singolo prodotto. In caso di allergie o esigenze specifiche, consulta sempre etichetta e scheda prima dell’acquisto.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Ci sono prodotti vegani, biologici o senza glutine?</summary><p>La gamma comprende referenze con queste caratteristiche. Ogni dichiarazione vale esclusivamente per il prodotto che la riporta nella propria scheda.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Come devo conservare un prodotto?</summary><p>Conservazione, shelf life e istruzioni dopo l’apertura cambiano da prodotto a prodotto e sono mostrate nella relativa scheda quando dichiarate dalla fonte Ugolini.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Come posso usare le specialità Ugolini?</summary><p>Le modalità d’uso disponibili sono indicate nella scheda prodotto. Sughi, pesti e condimenti sono pensati per un uso semplice sia nella cucina quotidiana sia in ambito professionale.</p></details><!-- /wp:details -->
</div></div><!-- /wp:group -->

<!-- wp:group {"className":"ugolini-faq-section","layout":{"type":"default"}} --><div class="wp-block-group ugolini-faq-section"><div><p class="ugolini-eyebrow">Ordini e spedizioni</p><h2 class="wp-block-heading">Acquisto e assistenza</h2></div><div class="wp-block-group ugolini-faq-list">
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Come posso effettuare un ordine?</summary><p>Scegli i prodotti nello shop, aggiungili al carrello e completa i dati richiesti dal checkout sicuro SureCart.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Quando verrà spedito il mio ordine?</summary><p>Tempi, disponibilità e modalità applicabili vengono mostrati nel checkout e nella conferma d’ordine. Per esigenze particolari contatta Ugolini prima dell’acquisto.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Come posso seguire la spedizione?</summary><p>Quando il vettore rende disponibile il tracciamento, i riferimenti vengono comunicati ai recapiti associati all’ordine.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Quanto costa la spedizione?</summary><p>Il costo applicabile viene calcolato e mostrato nel checkout prima della conferma, in base all’indirizzo e alle condizioni configurate nello store.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Posso modificare o annullare un ordine?</summary><p>Contatta il servizio clienti il prima possibile indicando il numero d’ordine. Una modifica può essere valutata solo prima che l’ordine venga elaborato e non può essere garantita.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Cosa devo fare se ricevo un prodotto errato o danneggiato?</summary><p>Fotografa confezione e prodotto e contatta subito il servizio clienti indicando il numero d’ordine, così il caso potrà essere verificato.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Come funzionano resi e rimborsi?</summary><p>Le condizioni applicabili dipendono dalla tipologia di prodotto e dallo stato dell’ordine. Consulta i termini dello store e contatta l’assistenza prima di restituire qualsiasi articolo.</p></details><!-- /wp:details -->
</div></div><!-- /wp:group -->

<!-- wp:group {"className":"ugolini-faq-section","layout":{"type":"default"}} --><div class="wp-block-group ugolini-faq-section"><div><p class="ugolini-eyebrow">Account e promozioni</p><h2 class="wp-block-heading">Area clienti</h2></div><div class="wp-block-group ugolini-faq-list">
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Devo creare un account per acquistare?</summary><p>Le opzioni disponibili vengono mostrate durante il checkout. L’area clienti consente di consultare gli ordini associati al proprio account.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Quali metodi di pagamento sono accettati?</summary><p>I metodi attivi e disponibili per l’ordine vengono mostrati direttamente nel checkout sicuro.</p></details><!-- /wp:details -->
<!-- wp:details {"open":true,"className":"ugolini-faq-item"} --><details open class="wp-block-details ugolini-faq-item"><summary>Come posso usare un codice promozionale?</summary><p>Quando una promozione è attiva, inserisci il codice nell’apposito campo del checkout. Validità e condizioni dipendono dalla singola iniziativa.</p></details><!-- /wp:details -->
</div></div><!-- /wp:group -->

</div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:pattern {"slug":"ugolini-group/b2b-cta"} /-->
