<?php
/**
 * Title: Page — Contatti
 * Slug: ugolini-group/page-contact
 * Categories: ugolini-pages
 * Keywords: contact, form, whatsapp
 * Block Types: core/post-content
 */
?>
<!-- wp:cover {"url":"https://ugolinigroup.com/wp-content/uploads/2026/08/8824-ragu-alla-bolognese-ugolini-gourmet-8.jpg","alt":"Ragù alla bolognese Ugolini Gourmet con pomodori italiani","dimRatio":68,"overlayColor":"dark-section","isUserOverlayColor":true,"align":"full","className":"ugolini-page-hero ugolini-page-hero--image"} --><div class="wp-block-cover alignfull ugolini-page-hero ugolini-page-hero--image"><span aria-hidden="true" class="wp-block-cover__background has-dark-section-background-color has-background-dim-70 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Ragù alla bolognese Ugolini Gourmet con pomodori italiani" src="https://ugolinigroup.com/wp-content/uploads/2026/08/8824-ragu-alla-bolognese-ugolini-gourmet-8.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"align":"wide","className":"ugolini-page-hero-content","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-page-hero-content"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Contattaci</p><!-- /wp:paragraph --><!-- wp:post-title {"level":1} /--><!-- wp:paragraph --><p>Hai una domanda? Scrivici un messaggio e ti risponderemo il prima possibile.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div><!-- /wp:cover -->
<!-- wp:group {"align":"full","className":"ugolini-section ugolini-contact-intro","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-contact-intro"><!-- wp:group {"align":"wide","className":"ugolini-contact-grid","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-contact-grid"><!-- wp:group {"className":"ugolini-contact-column","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-contact-column"><!-- wp:heading --><h2 class="wp-block-heading">Parliamo</h2><!-- /wp:heading --><!-- wp:list {"className":"ugolini-contact-list"} --><ul class="wp-block-list ugolini-contact-list"><li><?php echo ugolini_group_icon( 'mail' ); ?><a href="mailto:info@ugolinigroup.com">info@ugolinigroup.com</a></li><li><?php echo ugolini_group_icon( 'phone' ); ?><a href="tel:+393515111273">+39 351 511 1273</a></li><li><?php echo ugolini_group_icon( 'map-pin' ); ?><span>Via Tiberina km 9.2, 00060 Riano (RM), Italia</span></li></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://wa.me/393515111273" target="_blank" rel="noreferrer noopener"><?php echo ugolini_group_icon( 'message-circle' ); ?>Scrivici su WhatsApp</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->
<!-- wp:group {"className":"ugolini-contact-column ugolini-contact-commercial","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-contact-column ugolini-contact-commercial"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Richieste commerciali</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Per retail, ristorazione, distribuzione e collaborazioni B2B, indica azienda, paese e tipologia di interesse. Ti risponderemo appena possibile.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"align":"full","className":"ugolini-section ugolini-contact-form-section","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-contact-form-section"><!-- wp:group {"align":"wide","className":"ugolini-contact-form-heading","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-contact-form-heading"><!-- wp:heading --><h2 class="wp-block-heading">Lascia un messaggio</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Hai una domanda, una richiesta o vuoi conoscere meglio il mondo Ugolini Gourmet? Scrivici oppure chiamaci al <a href="tel:+393515111273">+39 351 511 1273</a>.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:html -->
<form class="ugolini-contact-form alignwide" action="mailto:info@ugolinigroup.com" method="post" enctype="text/plain">
	<label><span>Nome</span><input type="text" name="Nome" autocomplete="name" placeholder="Nome"></label>
	<label><span>Email</span><input type="email" name="Email" autocomplete="email" placeholder="Email" required></label>
	<label class="ugolini-contact-form__wide"><span>Azienda</span><input type="text" name="Azienda" autocomplete="organization" placeholder="Azienda"></label>
	<label class="ugolini-contact-form__wide"><span>Messaggio</span><textarea name="Messaggio" rows="7" placeholder="Come possiamo aiutarti?" required></textarea></label>
	<button class="ugolini-contact-form__wide" type="submit">Invia la richiesta</button>
	<p>L’invio apre il tuo programma di posta: il sito non conserva i dati inseriti.</p>
</form>
<!-- /wp:html --></div><!-- /wp:group -->
