<?php
/**
 * Title: Premium native SureCart product detail
 * Slug: ugolini-group/product-detail
 * Categories: ugolini-pages
 * Keywords: product, gallery, purchase, surecart
 * Inserter: no
 */
?>
<!-- wp:surecart/product-page {"align":"wide","className":"ugolini-product-page","layout":{"type":"constrained"}} -->
<!-- wp:html --><nav class="ugolini-product-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/shop/">Shop</a><span>/</span><span>Prodotto Ugolini</span></nav><!-- /wp:html -->
<!-- wp:columns {"align":"wide","className":"ugolini-product-columns"} --><div class="wp-block-columns alignwide ugolini-product-columns"><!-- wp:column {"width":"60%","className":"ugolini-product-gallery"} --><div class="wp-block-column ugolini-product-gallery" style="flex-basis:60%"><!-- wp:surecart/product-media {"auto_height":true,"show_thumbnails":true,"thumbnails_per_page":5,"lightbox":true} /--></div><!-- /wp:column -->
<!-- wp:column {"width":"40%","className":"ugolini-product-summary"} --><div class="wp-block-column ugolini-product-summary" style="flex-basis:40%"><!-- wp:surecart/product-title /--><!-- wp:group {"className":"ugolini-product-price","layout":{"type":"flex","flexWrap":"wrap"}} --><div class="wp-block-group ugolini-product-price"><!-- wp:surecart/product-selected-price-scratch-amount /--><!-- wp:surecart/product-selected-price-amount /--><!-- wp:surecart/product-selected-price-interval /--><!-- wp:surecart/product-sale-badge /--></div><!-- /wp:group --><!-- wp:surecart/product-description /--><!-- wp:surecart/product-variant-pills --><!-- wp:surecart/product-variant-pill /--><!-- /wp:surecart/product-variant-pills --><!-- wp:surecart/product-price-chooser --><!-- wp:surecart/product-price-choice-template --><!-- wp:surecart/price-name /--><!-- wp:group {"layout":{"type":"flex","flexWrap":"wrap"}} --><div class="wp-block-group"><!-- wp:surecart/price-scratch-amount /--><!-- wp:surecart/price-amount /--><!-- wp:surecart/price-interval /--></div><!-- /wp:group --><!-- /wp:surecart/product-price-choice-template --><!-- /wp:surecart/product-price-chooser --><!-- wp:surecart/product-quantity /--><!-- wp:surecart/product-buy-buttons {"style":{"spacing":{"blockGap":"8px"}}} --><div class="wp-block-surecart-product-buy-buttons wp-block-buttons sc-block-buttons is-layout-flex"><!-- wp:surecart/product-buy-button {"add_to_cart":true,"text":"Aggiungi al carrello"} /--><!-- wp:surecart/product-buy-button {"text":"Acquista ora","className":"is-style-outline"} /--></div><!-- /wp:surecart-product-buy-buttons -->
<!-- wp:html --><div class="ugolini-product-assurances" aria-label="Informazioni di acquisto"><span><?php echo ugolini_group_icon( 'badge-check' ); ?><strong>Qualità</strong> selezionata</span><span><?php echo ugolini_group_icon( 'package-check' ); ?><strong>Prodotto</strong> italiano</span><span><?php echo ugolini_group_icon( 'shield-check' ); ?><strong>Pagamenti</strong> protetti</span></div><!-- /wp:html -->
<!-- wp:details {"className":"ugolini-summary-detail"} --><details class="wp-block-details ugolini-summary-detail"><summary>Informazioni sul prodotto</summary><!-- wp:paragraph --><p>Ingredienti, allergeni, utilizzo e conservazione sono disponibili nella scheda dettagliata in questa pagina.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details {"className":"ugolini-summary-detail"} --><details class="wp-block-details ugolini-summary-detail"><summary>Spedizione e pagamenti</summary><!-- wp:paragraph --><p>Costi e tempi di consegna vengono confermati durante il checkout. I pagamenti sono gestiti tramite SureCart.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details {"className":"ugolini-summary-detail"} --><details class="wp-block-details ugolini-summary-detail"><summary>Assistenza Ugolini</summary><!-- wp:paragraph --><p>Per informazioni sul prodotto o richieste professionali contatta il team Ugolini.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:paragraph {"className":"ugolini-purchase-note"} --><p class="ugolini-purchase-note">Pagamenti protetti. Disponibilità e consegna vengono confermate al checkout.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- /wp:surecart/product-page -->
<!-- wp:group {"align":"full","className":"ugolini-product-information","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-product-information"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Dettagli del prodotto</p><!-- /wp:paragraph --><!-- wp:post-content {"layout":{"type":"constrained"}} /--></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"align":"full","className":"ugolini-section ugolini-related-products","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-related-products"><!-- wp:group {"align":"wide","className":"ugolini-section-heading","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-section-heading"><!-- wp:heading --><h2 class="wp-block-heading">Altre specialità Ugolini</h2><!-- /wp:heading --><!-- wp:paragraph {"className":"ugolini-editorial-link"} --><p class="ugolini-editorial-link"><a href="/shop/">Tutti i prodotti</a></p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:pattern {"slug":"ugolini-group/product-grid"} /--></div><!-- /wp:group -->
<!-- wp:group {"align":"full","className":"ugolini-section ugolini-product-after","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-section ugolini-product-after"><!-- wp:shortcode -->[ugolini_product_story]<!-- /wp:shortcode --><!-- wp:shortcode -->[ugolini_product_guide]<!-- /wp:shortcode --><!-- wp:shortcode -->[ugolini_cooking_suggestions]<!-- /wp:shortcode --></div><!-- /wp:group -->
<!-- wp:pattern {"slug":"ugolini-group/testimonials"} /-->
